[package]
name = "lore-proto"
authors.workspace = true
description = "A message setup for laurel server and client(s)"
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true
