version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "weekly"