[package]
name = "laurel-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

# [dependencies]
# tokio = { version = "1.47.0", features = ["full"] }
# uuid = { version = "1.17.0" }