name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install Dependencies
      run: sudo apt -y install capnproto -qq
    - name: Build
      run: cargo build --bin laurel-server --verbose
    - name: Run tests
      run: cargo test --bin laurel-server --verbose
