name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin laurel-server --verbose
    - name: Run Tests
      run: cargo test --bin laurel-server --verbose

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin laurel-server --verbose
    - name: Run Tests
      run: cargo test --bin laurel-server --verbose
