name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install Capn proto
      run: sudo apt-get install capnproto -qq; sudo apt-get -y install fontconfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
